version: "3.6"
services:
    db:
        container_name: db-postgres_12.5-alpine
        image: postgres:12.5-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=jarko
        ports:
            - 5432:5432
        volumes: 
            - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
